name: 'Check Tag'
description: 'Checks if a Git reference name has SemVer version'
runs:
  using: 'composite'
  steps:   
    - name: check tag
      shell: bash
      run: |
        if [[ ${{ github.ref_type }} == 'tag' && ${{ github.ref_name }} =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "tag name is valid"
        else
          echo "tag name is invalid"
          exit 1
        fi
